name: Bake Images (build only)

on:
  pull_request:
    branches: [main]
    paths:
      - docker-bake.hcl
      - images/**
      - justfile
      - .github/workflows/bake.yml
      - "!images/**/README.md"
      - "!README.md"
  
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: bake-images-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bake:
    runs-on: ubuntu-latest
    name: Bake Images (build only)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Bake images
        run: just bake